version: '3'

services:
  backend: &backend
    build:
      context: .
      dockerfile: Dockerfile
    image: revolutionapi/tradebox
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8006:8009"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8009

  ws-monitor:
    <<: *backend
    ports: []
    command: python ws_monitor.py --symbol=1000FLOKIUSDT


  prefect-server: &prefect
    image: prefecthq/prefect:2.19.8-python3.11
    restart: unless-stopped
    ports:
      - '4200:4200'
    env_file:
      - .env
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_URL=http://20.243.22.4:4200/api
      - PREFECT_API_URL=http://20.243.22.4:4200/api
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    volumes:
      - .docker/prefect:/root/.prefect
    command: prefect server start

  prefect-agent:
    <<: *prefect
    environment:
      - PREFECT_API_URL=http://20.243.22.4:4200/api
    ports: []
    command: prefect worker start --pool "local"


  postgres:
    image: postgres:16-alpine
    restart: always
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1z63W6IWWy
      - POSTGRES_DB=tradebox
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10


#  pgbouncer:
#    image: edoburu/pgbouncer:latest
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=1z63W6IWWy
#      - DB_PASSWORD=dbpassword
#      - ADMIN_USERS=postgres,admin
#    ports:
#      - "5432:6432"

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1z63W6IWWy
      - DB_HOST=postgres
      - DB_NAME=tradebox
      - AUTH_TYPE=scram-sha-256 # remove/comment this line if using postgres:13 and lower
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,dbuser
    ports:
      - "5432:5432"
    depends_on:
      - postgres

volumes:
  pgdata:
